import streamlit as st
from sklearn.preprocessing import PowerTransformer
from sklearn.ensemble import RandomForestClassifier

player_1 = st.selectbox(
    "Select Your first player",
    (' Erick Rowan',
    ' R-Truth',
    '"Big" Bronson Reed',
    'AJ Styles',
    'Adam Cole',
    'Adriana Rizzo',
    'Akam',
    'Akira Tozawa',
    'Alba Fyre',
    'Aleister Black',
    'Alexa Bliss',
    'Alicia Fox',
    'Amari Miller',
    'Andrade',
    'Andre Chase',
    'Angel',
    'Angel Garza',
    'Angelo Dawkins',
    'Anthony Alanis',
    'Apollo Crews',
    'Arianna Grace',
    'Asuka',
    'Austin Theory',
    'Ava',
    'Axiom',
    'Bad Bunny',
    'Baron Corbin',
    'Bayley',
    'Becky Lynch',
    'Berto',
    'Beth Phoenix',
    'Bianca Belair',
    'Big Bronson Reed',
    'Big E',
    'Billie Kay',
    'Blair Davenport',
    'Bobby Lashley',
    'Braun Strowman',
    'Bray Wyatt',
    'Bray Wyatt / The Fiend',
    'Brock Lesnar',
    'Bron Breakker',
    'Bronco Nima',
    'Bronson Reed',
    'Brooks Jensen',
    'Brutus Creed',
    'Buddy Murphy',
    'Butch',
    'CM Punk',
    'Cameron Grimes',
    'Candice LeRae',
    'Carlito',
    'Carmella',
    'Carmelo Hayes',
    'Cedric Alexander',
    'Cesaro',
    'Chad Gable',
    'Channing "Stacks" Lorenzo',
    'Channing Lorenzo',
    'Charlie Dempsey',
    'Charlotte Flair',
    'Chelsea Green',
    'Cody Rhodes',
    'Cora Jade',
    'Cruz Del Toro',
    'Curt Hawkins',
    'Dakota Kai',
    'Damage CTRL',
    'Damian Priest',
    'Damon Kemp',
    'Dana Brooke',
    'Dani Palmer',
    'Daniel Bryan',
    'Dante Chen',
    'Dijak',
    'Dolph Ziggler',
    'Dominik Mysterio',
    'Doudrop',
    'Dragon Lee',
    'Drew Gulak',
    'Drew McIntyre',
    'Duke Hudson',
    'Edge',
    'Elektra Lopez',
    'Elias',
    'Elton Prince',
    'Emma',
    'Erik',
    'Ethan Page',
    'Eva Marie',
    'Ezekiel',
    'Fabian Aichner',
    'Fallon Henley',
    'Finn Balor',
    'Gable Steveson',
    'Gigi Dolin',
    'Giovanni Vinci',
    'Giulia',
    'Goldberg',
    'Grayson Waller',
    'Gunther',
    'Hank Walker',
    'Happy Corbin',
    'Humberto Carrillo',
    'IYO SKY',
    'Ilja Dragunov',
    'Indi Hartwell',
    'Io Shirai',
    'Isla Dawn',
    'Ivar',
    'Ivy Nile',
    'Izzi Dame',
    'JD McDonagh',
    'Jacob Fatu',
    'Jacy Jayne',
    'Jade Cargill',
    'Jagger Reid',
    'Jaida Parker',
    'Jakara Jackson',
    'Jazmyn Nyx',
    "Je'Von Evans",
    'Jeff Hardy',
    'Jey Uso',
    'Jimmy Uso',
    'Jinder Mahal',
    'Joaquin Wilde',
    'Joe Coffey',
    'Joe Gacy',
    'Joe Hendry',
    'John Cena',
    'John Morrison',
    'Johnny Gargano',
    'Jordan Devlin',
    'Jordynne Grace',
    'Joseph Average',
    'Josh Briggs',
    'Julius Creed',
    'Kairi Sane',
    'Kalisto',
    'Karl Anderson',
    'Karmen Petrovic',
    'Karrion Kross',
    'Katana Chance',
    'Kay Lee Ray',
    'Kayden Carter',
    'Keith Lee',
    'Kelani Jordan',
    'Kendal Grey',
    'Kevin Owens',
    'Kiana James',
    'King Corbin',
    'Kit Wilson',
    'Kofi Kingston',
    "Kyle O'Reilly",
    'LA Knight',
    'Lacey Evans',
    'Lash Legend',
    'Lexis King',
    'Lince Dorado',
    'Lita',
    'Liv Morgan',
    'Logan Paul',
    'Lola Vice',
    'Lucien Price',
    'Ludwig Kaiser',
    'Luke Gallows',
    'Lyra Valkyria',
    'MVP',
    'Madcap Moss',
    'Malik Blade',
    'Mandy Rose',
    'Mansoor',
    'Many',
    'Marcel Barthel',
    'Mark Coffey',
    'Maryse',
    'Matt Riddle',
    'Maxxine Dupri',
    'Meiko Satomura',
    'Mia Yim',
    'Michin',
    'Montez Ford',
    'Murphy',
    'Mustafa Ali',
    'Myles Borne',
    'Naomi',
    'Nash Carter',
    'Natalya',
    'Nathan Frazer',
    'Nia Jax',
    'Nikki A.S.H.',
    'Nikki Cross',
    'Nikkita Lyons',
    'Noam Dar',
    'Nunzio',
    'Oba Femi',
    'Odyssey Jones',
    'Omos',
    'Oro Mensah',
    'Otis',
    'Pat McAfee',
    'Pete Dunne',
    'Peyton Royce',
    'Piper Niven',
    'R-Truth',
    'Randy Orton',
    'Raquel González',
    'Raquel Rodriguez',
    'Rey Mysterio',
    'Rhea Ripley',
    'Rick Boogs',
    'Ricochet',
    'Ridge Holland',
    'Riley Osborne',
    'Rip Fowler',
    'Robert Roode',
    'Roderick Strong',
    'Roman Reigns',
    'Ronda Rousey',
    'Roxanne Perez',
    'Ruby Riott',
    'SLAPJACK',
    'Sami Zayn',
    'Sanga',
    'Santos Escobar',
    'Sarah Logan',
    'Sasha Banks',
    'Seth "Freakin" Rollins',
    'Seth Rollins',
    'Shanky',
    'Shawn Spears',
    'Shayna Baszler',
    'Sheamus',
    'Shelton Benjamin',
    'Shinsuke Nakamura',
    'Shorty G',
    'Shotzi',
    'Sol Ruca',
    'Solo Sikoa',
    'Sonya Deville',
    'Stephanie Vaquer',
    'Tama Tonga',
    'Tamina',
    'Tatum Paxley',
    'Tavion Heights',
    'Tegan Nox',
    'The Brawling Brutes Ridge Holland',
    'The Brawling Brutes Sheamus',
    'The Gobbledy Gooker',
    'The Miz',
    'The Rock',
    'Thea Hail',
    'Theory',
    'Tiffany Stratton',
    'Timothy Thatcher',
    'Tommaso Ciampa',
    'Tonga Loa',
    'Toni Storm',
    "Tony D'Angelo",
    'Toxic Attraction (Mandy Rose, Gigi Dolin, Jacy Jayne)',
    'Trent Seven',
    'Trick Williams',
    'Trish Stratus',
    'Troy "Two Dimes" Donovan',
    'Tyler Bate',
    'Tyson DuPont',
    'Uriah Connors',
    'Valentina Feroz',
    'Veer',
    'Veer Mahaan',
    'Von Wagner',
    'WALTER',
    'Wendy Choo',
    'Wes Lee',
    'Wolfgang',
    'Wren Sinclair',
    'Xavier Woods',
    'Yulisa León',
    'Zachary Wentz',
    'Zack Ryder',
    'Zaria',
    'Zelina Vega',
    'Zoey Stark'),
    index=None,
    placeholder="Select your first player",
)

player_2 = st.selectbox(
    "Select Your second player",
    (' Erick Rowan',
    ' R-Truth',
    '"Big" Bronson Reed',
    'AJ Styles',
    'Adam Cole',
    'Adriana Rizzo',
    'Akam',
    'Akira Tozawa',
    'Alba Fyre',
    'Aleister Black',
    'Alexa Bliss',
    'Alicia Fox',
    'Amari Miller',
    'Andrade',
    'Andre Chase',
    'Angel',
    'Angel Garza',
    'Angelo Dawkins',
    'Anthony Alanis',
    'Apollo Crews',
    'Arianna Grace',
    'Asuka',
    'Austin Theory',
    'Ava',
    'Axiom',
    'Bad Bunny',
    'Baron Corbin',
    'Bayley',
    'Becky Lynch',
    'Berto',
    'Beth Phoenix',
    'Bianca Belair',
    'Big Bronson Reed',
    'Big E',
    'Billie Kay',
    'Blair Davenport',
    'Bobby Lashley',
    'Braun Strowman',
    'Bray Wyatt',
    'Bray Wyatt / The Fiend',
    'Brock Lesnar',
    'Bron Breakker',
    'Bronco Nima',
    'Bronson Reed',
    'Brooks Jensen',
    'Brutus Creed',
    'Buddy Murphy',
    'Butch',
    'CM Punk',
    'Cameron Grimes',
    'Candice LeRae',
    'Carlito',
    'Carmella',
    'Carmelo Hayes',
    'Cedric Alexander',
    'Cesaro',
    'Chad Gable',
    'Channing "Stacks" Lorenzo',
    'Channing Lorenzo',
    'Charlie Dempsey',
    'Charlotte Flair',
    'Chelsea Green',
    'Cody Rhodes',
    'Cora Jade',
    'Cruz Del Toro',
    'Curt Hawkins',
    'Dakota Kai',
    'Damage CTRL',
    'Damian Priest',
    'Damon Kemp',
    'Dana Brooke',
    'Dani Palmer',
    'Daniel Bryan',
    'Dante Chen',
    'Dijak',
    'Dolph Ziggler',
    'Dominik Mysterio',
    'Doudrop',
    'Dragon Lee',
    'Drew Gulak',
    'Drew McIntyre',
    'Duke Hudson',
    'Edge',
    'Elektra Lopez',
    'Elias',
    'Elton Prince',
    'Emma',
    'Erik',
    'Ethan Page',
    'Eva Marie',
    'Ezekiel',
    'Fabian Aichner',
    'Fallon Henley',
    'Finn Balor',
    'Gable Steveson',
    'Gigi Dolin',
    'Giovanni Vinci',
    'Giulia',
    'Goldberg',
    'Grayson Waller',
    'Gunther',
    'Hank Walker',
    'Happy Corbin',
    'Humberto Carrillo',
    'IYO SKY',
    'Ilja Dragunov',
    'Indi Hartwell',
    'Io Shirai',
    'Isla Dawn',
    'Ivar',
    'Ivy Nile',
    'Izzi Dame',
    'JD McDonagh',
    'Jacob Fatu',
    'Jacy Jayne',
    'Jade Cargill',
    'Jagger Reid',
    'Jaida Parker',
    'Jakara Jackson',
    'Jazmyn Nyx',
    "Je'Von Evans",
    'Jeff Hardy',
    'Jey Uso',
    'Jimmy Uso',
    'Jinder Mahal',
    'Joaquin Wilde',
    'Joe Coffey',
    'Joe Gacy',
    'Joe Hendry',
    'John Cena',
    'John Morrison',
    'Johnny Gargano',
    'Jordan Devlin',
    'Jordynne Grace',
    'Joseph Average',
    'Josh Briggs',
    'Julius Creed',
    'Kairi Sane',
    'Kalisto',
    'Karl Anderson',
    'Karmen Petrovic',
    'Karrion Kross',
    'Katana Chance',
    'Kay Lee Ray',
    'Kayden Carter',
    'Keith Lee',
    'Kelani Jordan',
    'Kendal Grey',
    'Kevin Owens',
    'Kiana James',
    'King Corbin',
    'Kit Wilson',
    'Kofi Kingston',
    "Kyle O'Reilly",
    'LA Knight',
    'Lacey Evans',
    'Lash Legend',
    'Lexis King',
    'Lince Dorado',
    'Lita',
    'Liv Morgan',
    'Logan Paul',
    'Lola Vice',
    'Lucien Price',
    'Ludwig Kaiser',
    'Luke Gallows',
    'Lyra Valkyria',
    'MVP',
    'Madcap Moss',
    'Malik Blade',
    'Mandy Rose',
    'Mansoor',
    'Many',
    'Marcel Barthel',
    'Mark Coffey',
    'Maryse',
    'Matt Riddle',
    'Maxxine Dupri',
    'Meiko Satomura',
    'Mia Yim',
    'Michin',
    'Montez Ford',
    'Murphy',
    'Mustafa Ali',
    'Myles Borne',
    'Naomi',
    'Nash Carter',
    'Natalya',
    'Nathan Frazer',
    'Nia Jax',
    'Nikki A.S.H.',
    'Nikki Cross',
    'Nikkita Lyons',
    'Noam Dar',
    'Nunzio',
    'Oba Femi',
    'Odyssey Jones',
    'Omos',
    'Oro Mensah',
    'Otis',
    'Pat McAfee',
    'Pete Dunne',
    'Peyton Royce',
    'Piper Niven',
    'R-Truth',
    'Randy Orton',
    'Raquel González',
    'Raquel Rodriguez',
    'Rey Mysterio',
    'Rhea Ripley',
    'Rick Boogs',
    'Ricochet',
    'Ridge Holland',
    'Riley Osborne',
    'Rip Fowler',
    'Robert Roode',
    'Roderick Strong',
    'Roman Reigns',
    'Ronda Rousey',
    'Roxanne Perez',
    'Ruby Riott',
    'SLAPJACK',
    'Sami Zayn',
    'Sanga',
    'Santos Escobar',
    'Sarah Logan',
    'Sasha Banks',
    'Seth "Freakin" Rollins',
    'Seth Rollins',
    'Shanky',
    'Shawn Spears',
    'Shayna Baszler',
    'Sheamus',
    'Shelton Benjamin',
    'Shinsuke Nakamura',
    'Shorty G',
    'Shotzi',
    'Sol Ruca',
    'Solo Sikoa',
    'Sonya Deville',
    'Stephanie Vaquer',
    'Tama Tonga',
    'Tamina',
    'Tatum Paxley',
    'Tavion Heights',
    'Tegan Nox',
    'The Brawling Brutes Ridge Holland',
    'The Brawling Brutes Sheamus',
    'The Gobbledy Gooker',
    'The Miz',
    'The Rock',
    'Thea Hail',
    'Theory',
    'Tiffany Stratton',
    'Timothy Thatcher',
    'Tommaso Ciampa',
    'Tonga Loa',
    'Toni Storm',
    "Tony D'Angelo",
    'Toxic Attraction (Mandy Rose, Gigi Dolin, Jacy Jayne)',
    'Trent Seven',
    'Trick Williams',
    'Trish Stratus',
    'Troy "Two Dimes" Donovan',
    'Tyler Bate',
    'Tyson DuPont',
    'Uriah Connors',
    'Valentina Feroz',
    'Veer',
    'Veer Mahaan',
    'Von Wagner',
    'WALTER',
    'Wendy Choo',
    'Wes Lee',
    'Wolfgang',
    'Wren Sinclair',
    'Xavier Woods',
    'Yulisa León',
    'Zachary Wentz',
    'Zack Ryder',
    'Zaria',
    'Zelina Vega',
    'Zoey Stark'),
    index=None,
    placeholder="Select your second player",
)


Event_name = st.selectbox(
    "Select Your Event Name",
    ('NXT',
    'NXT 2300',
    'NXT Battleground',
    'NXT Deadline',
    'NXT Halloween Havoc',
    'NXT Heatwave',
    'NXT In Your House',
    "NXT New Year's Evil",
    'NXT No Mercy',
    'NXT Roadblock',
    "NXT Spring Breakin'",
    'NXT Stand & Deliver',
    'NXT The Great American Bash',
    'NXT Vengeance Day',
    'NXT WarGames',
    'NXT Worlds Collide',
    'WWE Backlash',
    'WWE Bad Blood',
    'WWE Bash in Berlin',
    'WWE Clash at the Castle: Scotland',
    'WWE Clash of Champions',
    'WWE Crown Jewel',
    'WWE Draft',
    'WWE Elimination Chamber',
    'WWE Extreme Rules',
    'WWE Fastlane',
    'WWE Hell in a Cell',
    'WWE King and Queen of the Ring',
    'WWE King of the Ring',
    'WWE Money in the Bank',
    'WWE Night of Champions',
    'WWE Payback',
    'WWE RAW',
    'WWE Royal Rumble',
    'WWE Royal Rumble 2023',
    "WWE Saturday Night's Main Event XXXVII",
    'WWE SmackDown',
    'WWE SummerSlam',
    'WWE Super ShowDown',
    'WWE Superstar Spectacle',
    'WWE Survivor Series',
    'WWE TLC',
    'WWE The Horror Show',
    'WWE Tribute To The Troops',
    'WWE Worlds Collide',
    'WWE WrestleMania Backlash',
    'WWE WrestleMania SmackDown',
    'WWE WrestleMania XL'),
    index=None,
    placeholder="Select the event",
)

title_match = st.selectbox(
    "Do you want to make this a title match",
    ('Yes', 'No'),
    index=None,
    placeholder="Is it yes/no?",
)

number = st.number_input("When do you want the match to take place", placeholder="when?/kab?/eppudu??", step=1, format="%d")
year = int(number)


import pickle 


scaler_path = r'scaler.pkl'
transformer_path = r"transformer.pkl"
model_path = r"rf_best_model.pkl"

pl_encoding_path = r"pl_encoding.pkl"
event_encoding_path = r"event_encoding.pkl"
title_encoding_path = r"title_encoding.pkl"

with open(pl_encoding_path, 'rb') as file:
    pl_encoding = pickle.load(file)

# Load the event encoding dictionary
with open(event_encoding_path, 'rb') as file:
    event_encoding = pickle.load(file)

# Load the title encoding dictionary
with open(title_encoding_path, 'rb') as file:
    title_encoding = pickle.load(file)

# Load the scaler
with open(scaler_path, 'rb') as file:
    ss_model = pickle.load(file)

# Load the transformer
with open(transformer_path, 'rb') as file:
    pt_object = pickle.load(file)

# Load the trained model
with open(model_path, 'rb') as file:
    rf_best_model = pickle.load(file)

def player_probs(a,b,c,d,e):
    b_enc = pl_encoding[b]
    c_enc = pl_encoding[c]
    a_enc = event_encoding[a]
    d_enc = title_encoding[d]
    features = [[a_enc, b_enc, c_enc, d_enc, e]]

    scaled = ss_model.transform(features)
    trans = pt_object.transform(scaled)

    a4 = trans[0, 0] * trans[0, 4]  
    a1, a2, a3 = trans[0, 1], trans[0, 2], trans[0, 3]

    probs = rf_best_model.predict_proba([[a1, a2, a3, a4]])
    return [f"The probability of {b} is {probs[0][0]:.2f} and the probability of {c} is {probs[0][1]:.2f}", probs]

import plotly.graph_objects as go

import requests
from PIL import Image, ImageDraw
import plotly.graph_objects as go
import base64
from io import BytesIO

# Function to download an image from a URL
def download_image_from_url(url):
    response = requests.get(url)
    response.raise_for_status()  # Check if the request was successful
    return Image.open(BytesIO(response.content)).convert("RGBA")

# Function to make an image circular
def make_image_circular(image):
    width, height = image.size
    # Create a circular mask
    mask = Image.new("L", (width, height), 0)
    draw = ImageDraw.Draw(mask)
    draw.ellipse((0, 0, width, height), fill=255)
    # Apply the mask to the image
    circular_img = Image.new("RGBA", (width, height))
    circular_img.paste(image, (0, 0), mask)
    return circular_img

# Function to convert an image to base64 (for use in Plotly)
def convert_image_to_base64(image):
    buffer = BytesIO()
    image.save(buffer, format="PNG")
    buffer.seek(0)
    img_str = "data:image/png;base64," + base64.b64encode(buffer.getvalue()).decode()
    return img_str

def plot_confidence_with_images(probs, player_1, player_2):
    # Generate dynamic image URLs
    img_url_1 = f"https://www.thesmackdownhotel.com/images/wrestling/wrestlers/full-body/{player_1.replace(' ', '-').lower()}.png"
    img_url_2 = f"https://www.thesmackdownhotel.com/images/wrestling/wrestlers/full-body/{player_2.replace(' ', '-').lower()}.png"
    
    default_image = "https://fanatics.frgimages.com/john-cena-and-cody-rhodes-wwe-unsigned-2025-elimination-chamber-hug-photograph_ss5_p-202975932+u-wwvtfsnodave4ij2zv5n+v-0eih00sbu919pgfzp5bs.jpg?_hv=2&w=900"


    try:
        img_1 = make_image_circular(download_image_from_url(img_url_1))
    except Exception as e:
        img_1 = make_image_circular(download_image_from_url(default_image))
    try:
        img_2 = make_image_circular(download_image_from_url(img_url_2))
    except Exception as e:
        img_2 = make_image_circular(download_image_from_url(default_image))
    
    img_player_1 = convert_image_to_base64(img_1)
    img_player_2 = convert_image_to_base64(img_2)

    # Use numeric positions for bars and images
    fig = go.Figure()
    fig.add_trace(go.Bar(name=player_1, x=[0], y=[probs[0]], marker_color='blue', width = 0.3))
    fig.add_trace(go.Bar(name=player_2, x=[1], y=[probs[1]], marker_color='red', width = 0.3))

    fig.add_layout_image(
        dict(
            source=img_player_1,
            x=0,
            y=probs[0] + 0.01,
            xref="x",
            yref="y",
            sizex=0.2,
            sizey=0.2,
            xanchor="center",
            yanchor="bottom"
        )
    )
    fig.add_layout_image(
        dict(
            source=img_player_2,
            x=1,
            y=probs[1] + 0.01,
            xref="x",
            yref="y",
            sizex=0.2,
            sizey=0.2,
            xanchor="center",
            yanchor="bottom"
        )
    )

    # Update x-axis with player names as labels
    fig.update_layout(
        xaxis=dict(
            categoryorder='array',
            categoryarray=[player_1, player_2],
            tickmode='array',
            tickvals=[0, 1],
            ticktext=[player_1, player_2]
        ),
        barmode='group',
        title='Winning Probability',
        yaxis=dict(title='Probability', range=[0, 1])
    )
    
    return fig




if st.button("Let's Predict"):
    result = player_probs(Event_name, player_1, player_2, title_match, year)
    probs = [result[1][0][0], result[1][0][1]]
    fig = plot_confidence_with_images(probs, player_1, player_2)
    st.plotly_chart(fig, use_container_width=True)
    st.write(result[0])

